services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html/ # Mount folder proyek lokal ke dalam container web
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: eparking_db
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d # Mengimpor SQL dari folder 'database'